INSERT INTO `states`(`id`,`short_name`,`name`) VALUES 
( '1', 'AS', 'AGUASCALIENTES' ),
( '2', 'BC', 'BAJA CALIFORNIA' ),
( '3', 'BS', 'BAJA CALIFORNIA SUR' ),
( '4', 'CC', 'CAMPECHE' ),
( '5', 'CL', 'COAHUILA DE ZARAGOZA' ),
( '6', 'CM', 'COLIMA' ),
( '7', 'CS', 'CHIAPAS' ),
( '8', 'CH', 'CHIHUAHUA' ),
( '9', 'DF', 'CIUDAD DE MEXICO' ),
( '10', 'DG', 'DURANGO' ),
( '11', 'GT', 'GUANAJUATO' ),
( '12', 'GR', 'GUERRERO' ),
( '13', 'HG', 'HIDALGO' ),
( '14', 'JC', 'JALISCO' ),
( '15', 'MC', 'ESTADO DE MEXICO' ),
( '16', 'MN', 'MICHOACAN DE OCAMPO' ),
( '17', 'MS', 'MORELOS' ),
( '18', 'NT', 'NAYARIT' ),
( '19', 'NL', 'NUEVO LEON' ),
( '20', 'OC', 'OAXACA' ),
( '21', 'PL', 'PUEBLA' ),
( '22', 'QT', 'QUERETARO' ),
( '23', 'QR', 'QUINTANA ROO' ),
( '24', 'SP', 'SAN LUIS POTOSI' ),
( '25', 'SL', 'SINALOA' ),
( '26', 'SR', 'SONORA' ),
( '27', 'TC', 'TABASCO' ),
( '28', 'TS', 'TAMAULIPAS' ),
( '29', 'TL', 'TLAXCALA' ),
( '30', 'VZ', 'VERACRUZ' ),
( '31', 'YN', 'YUCATAN' ),
( '32', 'ZS', 'ZACATECAS' );